CREATE SCHEMA TECHAPP;
CREATE TABLE TECHAPP.EVENT (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  EVENT_ID VARCHAR(100) NOT NULL,
  EVENT_NM VARCHAR(100) NOT NULL,
  EVENT_DATE DATE,
  HOMEPAGE VARCHAR(256)
);
DROP TABLE TECHAPP.EVENT;
